// /**
//  * Exporting components
//  */
export * from './bag-modal-component';
export * from './banner-component';
export * from './cart-description-component';
export * from './checkout-component';
// export * from './customize-lenses-component';
export * from './customized-lens-review-component';
export * from './checkout-guest-component';
export * from './checkout-thankyou-component';
export * from './control-messages-component';
export * from './description-component';
export * from './error-component';
export * from './email-modal-component';
export * from './footer-component';
export * from './forgot-password-component';
export * from './header-component';
export * from './home-component';
export * from './image-modal-component';
export * from './limit-component';
export * from './login-component';
export * from './must-haves-component';
export * from './new-arrivals-component';
export * from './product-carousel-component';
export * from './product-detail-component';
export * from './product-listing-component';
export * from './product-tile-component';
export * from './register-user-component';
export * from './reset-password-component';
export * from './sale-component';
export * from './select-lense-modal-component';
export * from './shop-ano-component';
export * from './subscribe-modal-component';
export * from './subscribe-component';
export * from './virtual-try-on-component';
export * from './user-account-component';
export * from './trial-history-component';
export * from './about-us-component';
// export * from './user-prescriptions-component';
// export * from './user-history-component';
export * from './user-address-book-component';
export * from './user-account-info-component';
export * from './faq-component';
export * from './location-component';
export * from './press-component';
export * from './quality-component';
export * from './kiosk-mode-component';
export * from './breadcrumb-component';
export * from './tool-tip-component';
export * from './loader-component';
export * from './image-zoom-component';
export * from './ditto-control';
export * from './continue-shopping-component';

export * from './banner-component';
